- README.md
If `request` is not passed to `generateToken`, then `getSecret` can't get request like `(request) => ...`
> Update generateToken in README.md

- README.md
- src/index.ts
- src/tests/testsuite.ts
To align things more with the old `csurf` API, making `csrf-csrf` a much easier plug and replace alternative, this brings the old `csrfToken` method back onto the request. This means it is no longer necessary to (but you still can) import `generateToken`.
> feat: expose generateToken via req.csrfToken

- README.md
- example/complete/package.json
- example/complete/src/index.js
- example/simple/package.json
- example/simple/src/index.js
- package-lock.json
- package.json
- src/index.ts
- src/tests/testsuite.ts
When using the double submit cookie pattern, http only should always be true for the cookie. Disabling this is not a good idea. It could be argued that if you're vulnerable to XSS, then CSRF doesn't matter, but there is no justification for negligence.
> Enforce http only option

- README.md
Adds the async example to the doc, this will fix issue #5
> docs: add async example

- SECURITY.md
Bumping supported version to >= v2.3.0 due to the dev audit fixes and the enforce http only change.
> chore: bump security supported version

- README.md
- src/index.ts
- src/tests/testsuite.ts
- src/tests/utils/helpers.ts
- src/tests/utils/mock.ts
Reuse token from existing session cookie.
This enables multitab support by not overwriting existing csrf cookies. 
Functionality can be toggled with the param 'overwrite', which defaults to true (reusability of tokens is disabled by default).
> Reuse session csrf token

- src/index.ts
> feat: allow to override cookie's httpOnly flag

- README.md
- src/index.ts
- src/tests/doublecsrf.test.ts
- src/tests/testsuite.ts
- src/types.ts
Exposes the statusCode, message, and code parameters for the error initialization
This will fix issue #55
> feat: allow customizable error

- README.md
- src/index.ts
- src/tests/getSessionIdentifier.test.ts
- src/tests/utils/helpers.ts
- src/tests/utils/mock.ts
- src/types.ts
Natively support session <> CSRF token association so CSRF tokens are only valid for the session they are generated for.
> feat: support optional stateless association of token with session

- README.md
While taking a look at the README for the project, I noticed an errant character and a broken link on the npm page due to no scheme in the URL. I looked at the file and noticed a couple of other things too.Just thought I'd try to make the world a (very slightly) better place with some small fixes. Here is the list:
1. Removed some spaces between the `href="` and the URL.
2. Added `https://` in front of a URL so that it would link properly from NPM's copy.
3. Removed a seemingly accidental `f`.
4. Added the link to the Patreon for this project because it was missing.
I realize this doesn't really add _much_ value to the project, but I hope it helps just a little. Thanks for a great library!
> Fix some very minor README defects

- .github/workflows/build-and-test.yml
- .gitignore
- biome.json
- example/complete/src/index.js
- package.json
- src/index.ts
- tsconfig.cjs.json
- tsconfig.json
- tsconfig.lint.json
- tsup.config.ts
* Flattens the build output.
* Changed output from lib to dist.
* Rely on tsup to output with Node 14 compatibility. Only build and test with Node 20.
* Perhaps tests should be added that test running the built package with Node 14/16/18/20.
* The package doesn't need to be build time compatible with < Node 20, only run time.
> build: fix the broken tsup setup

- README.md
- src/index.ts
- src/tests/doublecsrf.test.ts
- src/tests/skipCsrfProtection.test.ts
- src/types.ts
This brings a new optional and backwards compatible feature.
A discussion on the Discord led me to realise that if you wanted or needed a global way or a dynamic way to determine whether CSRF protection should be skipped for any given request, the only way to do this was by wrapping the `doubleCsrfProtection` middleware in your own middleware.
This PR brings in the `skipCsrfProtection` callback option to solve this use case. This allows users to explicitly avoid CSRF protection for cases where a native app is calling the same API's as a web based app, or in rare cases where specific requests do not require protection.
The documentation has been updated with extreme caution towards using this option and advises not to introduce vulnerabilities. `csrf-csrf` itself is explicitly checking the …
> feat: add optional skipCsrfProtection callback config option

- src/types.ts
Fixes #95, incorrect typing on `Request#csrfToken` making the `validateOnReuse` parameter inaccessible, which is potentially critical given it currently defaults to true.
> Fix v3/fix incorrect csrf token helper type

- src/types.ts
Fixes https://github.com/Psifi-Solutions/csrf-csrf/issues/95, incorrect typing on `Request#csrfToken` making the `validateOnReuse` parameter inaccessible, which is potentially critical given it currently defaults to true.
> fix(types): fix incorrect type for Request#csrfToken

- README.md
- src/index.ts
- src/tests/doublecsrf.test.ts
- src/tests/testsuite.ts
- src/types.ts
BREAKING CHANGE: If you were previously dependent on the sameSite value being 'lax' and you weren't explicitly setting it then you will need to set it now.
The reason for this change is to try and make csrf-csrf more secure by default. The idea being that when you need to make a change to the configuration, you should be actively thinking about that change and determining whether it is correct. This is to help encourage people to consult the documentation regarding configuration considerations.
> feat!: change default value of sameSite to 'strict'

- README.md
- src/index.ts
- src/tests/testsuite.ts
- src/types.ts
This is non-breaking as it reverts a previously unreleased breaking change to false. The change means less breaking changes with v4, less risk, and the WIP v4 documentation is intended to try and better guide users around appropriate configuration.
The idea is that users should be properly determining whether a particular config change is appropriate, they should make sure they understand what the configuration does and what impact changing it may have.
> feat: set httpOnly default back to true

- README.md
- src/index.ts
BREAKING CHANGE: If you were previously relying on either the generateToken or req.csrfToken functions throwing an error when the current CSRF token cookie is invalid, you will need to manually set validateOnReuse to false.
An error will no longer be thrown by default, a new token will be generated and returned instead. If you previously had this manually set to false, this is no longer necessary as it is now the default value.
> feat!: change validateOnReuse to false by default

- src/types.ts
Adds an explicit type for the csrfToken utility function added to the Request object for convenience.
> feat(types): add CsrfTokenGeneratorRequestUtil type

- README.md
Just a minor tweak to some of the documentation around `getSessionIdentifier`
> docs(README): clarify use of getSessionIdentifier

- README.md
- src/index.ts
- src/tests/testsuite.ts
- src/tests/utils/mock.ts
Logic for `validateOnReuse` parameter is still incorrect. If `validateOnReuse` is false, overwrite is true, but the token from the cookie is invalid, this should silently fail and return a new valid token instead.
> fix: validateOnReuse incorrectly throws

- package-lock.json
Bump vite transitive dependency of vitest to fix non-consequential vulnerability. Does not actually impact csrf-csrf.
> chore: bump transitive vitest dependency
